FROM python:3.8-slim

WORKDIR /app

COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Install Terraform
RUN apt-get update && apt-get install -y wget unzip \
    && wget https://releases.hashicorp.com/terraform/1.1.0/terraform_1.1.0_linux_amd64.zip \
    && unzip terraform_1.1.0_linux_amd64.zip \
    && mv terraform /usr/local/bin/ \
    && rm terraform_1.1.0_linux_amd64.zip

COPY . .

CMD ["python", "app.py"]
