import { z } from "zod"

export const diagramSchema = z.object({
  diagram: z
    .string()
    .describe(
      "The architecture diagram generated by the model with the format https://diagrams.mingrammer.com/"
    )
})
