import { z } from "zod"

export const diagramSchema = z.object({
  diagram: z
    .string()
    .describe(
      "The architecture diagram generated by the model with the format https://diagrams.mingrammer.com/"
    )
})

export const explainationSchema = z.object({
  explaination: z
    .string()
    .describe(
      "The explaination of system architecture with Markdown format"
    )
})